# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infra < Formula
  desc ""
  homepage "https://github.com/oliverteo288/infra"
  version "5.0.1"

  on_macos do
    url "https://github.com/OliverTeo288/infra/releases/download/5.0.1/infra_5.0.1_darwin_all.tar.gz"
    sha256 "a2da7fbe87f23507b0cbc995cad78281d4a7a59a6ee6c290ed19d34940eaa0ee"

    def install
      bin.install "infra"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OliverTeo288/infra/releases/download/5.0.1/infra_5.0.1_linux_amd64.tar.gz"
        sha256 "6f2350f5d1712dc4310ef13c5653f53ad3b5efec0c669f6bc19a1d6a5d4c2f37"

        def install
          bin.install "infra"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OliverTeo288/infra/releases/download/5.0.1/infra_5.0.1_linux_arm64.tar.gz"
        sha256 "2dcff417210a3c73851cdff7adfc9ce9fd8bd2041ccae1aa2144726216f4fa3e"

        def install
          bin.install "infra"
        end
      end
    end
  end
end
