# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infra < Formula
  desc ""
  homepage "https://github.com/oliverteo288/infra"
  version "5.1.3"

  on_macos do
    url "https://github.com/OliverTeo288/infra/releases/download/5.1.3/infra_5.1.3_darwin_all.tar.gz"
    sha256 "27b779f7772f0f3c217881545a3cdd5502ba44eb7b01ef2dd973873baca8b36d"

    def install
      bin.install "infra"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OliverTeo288/infra/releases/download/5.1.3/infra_5.1.3_linux_amd64.tar.gz"
        sha256 "3c442aec12c0159d0f9a2155cafefcea23f80235292ef9cd072e0371207643fa"

        def install
          bin.install "infra"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/OliverTeo288/infra/releases/download/5.1.3/infra_5.1.3_linux_arm64.tar.gz"
        sha256 "693adb0e0e4c5fbcf8535dc41a4761324303da61397a0ae8e7d321de0a0d3eda"

        def install
          bin.install "infra"
        end
      end
    end
  end
end
